title: 西遊記
description: 故事糖果屋：西遊記
time: Mon, 25 Mar 2024 08:37:44 +0000
type: m4a
items:
  - title: 01. 水濂洞美猴王，靈台方寸山學仙法
    size: 15711198
    duration: 971
  - title: 02. 混世魔王惹錯人，大鬧龍宮要兵器
    size: 11439417
    duration: 707
  - title: 03. 齊天大聖孫悟空，大鬧天宮眾神怒
    size: 11939433
    duration: 738
  - title: 04. 如來佛祖手掌心，悟空關押五行山
    size: 9275710
    duration: 573
  - title: 05. 玄奘改名唐三藏，緊箍咒語治悟空
    size: 20259095
    duration: 1252
  - title: 06. 山谷收服白龍馬，寺廟袈裟黑風怪
    size: 13982064
    duration: 864
  - title: 07. 黑風山上取袈裟，觀音菩薩神救援
    size: 11221214
    duration: 693
  - title: 08. 高老莊中捉妖怪，唐僧收服二弟子
    size: 11004439
    duration: 680
  - title: 09. 黃風洞有黃風怪，靈吉菩薩來鎮壓
    size: 16181084
    duration: 1000
  - title: 10. 八百流沙三千深，妖怪變成三弟子
    size: 11456875
    duration: 708
  - title: 11. 西方取經路遙遙，考驗決心狀況多
    size: 14028100
    duration: 867
  - title: 12. 五莊觀有人蔘果，偷吃果子打屁屁
    size: 18418929
    duration: 1138
  - title: 13. 白骨精詭計多端，悟空委屈難招架
    size: 9257645
    duration: 572
  - title: 14. 拯救寶象三公主，悟空大勝黃袍怪
    size: 16882521
    duration: 1043
  - title: 15. 孫行者七十二變，金角銀角被收服
    size: 18691532
    duration: 1155
  - title: 16. 取經夜宿林寶寺，真假唐僧難辨識
    size: 15230411
    duration: 941
  - title: 17. 火雲洞主紅孩兒，觀音收服再教育
    size: 15905033
    duration: 983
  - title: 18. 黑水河妖怪作亂，河神回歸速報恩
    size: 10174694
    duration: 628
  - title: 19. 車遲國三仙鬥法，孫悟空以法收妖
    size: 19976579
    duration: 1234
  - title: 20. 陳家莊妖怪作亂，收妖度過通天河
    size: 15498340
    duration: 958
  - title: 21. 武器黑洞金剛圈，收服妖怪度難關
    size: 20071967
    duration: 1240
  - title: 22. 西梁女國換關文，擺脫纏人蠍子精
    size: 17867623
    duration: 1104
  - title: 23. 唐僧驅趕孫悟空，真假悟空難辨認
    size: 20256298
    duration: 1252
  - title: 24. 火焰山鬥牛魔王，鐵扇公主芭蕉扇
    size: 20438290
    duration: 1263
  - title: 25. 祭賽國裡金光寺，悟空捉妖伏龍寺
    size: 15829112
    duration: 978
  - title: 26. 小雷音寺黃眉怪，彌勒金鐃後天袋
    size: 17397142
    duration: 1075
  - title: 27. 千年稀柿今朝淨，七絕衚衕此日開
    size: 12209743
    duration: 754
  - title: 28. 妖魔寶放煙沙火，悟空計盜紫金鈴
    size: 20153376
    duration: 1245
  - title: 29. 盤絲洞滅蜘蛛精，黃花觀收蜈蚣精
    size: 12811154
    duration: 791
  - title: 30. 獅駝嶺有三妖王，佛祖菩薩來降妖
    size: 22823073
    duration: 1410
  - title: 31. 比丘國妖怪作亂，南極壽星來助陣
    size: 11602772
    duration: 717
  - title: 32. 妖怪逼婚嫁唐僧，悟空請神來救援
    size: 17526362
    duration: 1083
  - title: 33. 滅法國王殺和尚，全剃光頭才醒悟
    size: 11376917
    duration: 703
  - title: 34. 開路先鋒是八戒，拯救師父是關鍵
    size: 14616458
    duration: 903
  - title: 35. 郡侯過錯成旱災，誠心補足感動天
    size: 8401670
    duration: 519
  - title: 36. 玉華王府收三徒，天尊收復九頭獅
    size: 22342169
    duration: 1381
  - title: 37. 三大妖王愛香油，四木禽星來抓妖
    size: 15383902
    duration: 950
  - title: 38. 悟空依婚降妖計，嫦娥星君接玉兔
    size: 23951848
    duration: 1480
  - title: 39. 拯救善人寇員外，洗刷冤屈取經去
    size: 10578374
    duration: 653
  - title: 40. 西方取經歸大唐，神佛仙各歸本位
    size: 20771687
    duration: 1284
